name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: AdityaPandey-DEV/snk@main
        with:
          github_user_name: AdityaPandey-DEV
          outputs: |
            dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v4
        with:
          name: contribution-snake
          path: dist/github-contribution-grid-snake.svg
